org.gradle.daemon=false
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# JER
modName=Just Enough Resources
modFileName=JustEnoughResources
modId=jeresources
modAuthor=way2muchnoise
modGroup=jeresources
modJavaVersion=25
githubUrl=github.com/way2muchnoise/JustEnoughResources
specificationVersion=1.9.0.31

# Minecraft
minecraftVersion=26.1.2
minecraftVersionRange=[26.1.2, 26.2)

# Fabric
fabricVersion=0.147.0+26.1.2
fabricLoaderVersion=0.19.2

# JEI
jeiVersion=29.5.0.27

# Fabric Config screen
clothVersion=26.1.154
modmenuVersion=17.0.0
